Moving monitor outputs used by the server to central storage
spacetelescope/jwql pull request #1397
Opened 2023-11-08 21:23 UTC by york-stsci

This is the code change part of issue 1395. Before it is merged, all in-use config.json files should be updated to contain a "working" key, whose value should initially be set to the same value as the "outputs" key.

2023-11-08 21:23 UTC, pep8speaks commented
Hello @york-stsci, Thank you for updating !







* In the file [`jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py`](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py):

> [Line 994:92](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L994): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator
> [Line 995:15](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L995): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 1000:111](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L1000): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator
> [Line 1141:98](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L1141): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1142:19](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L1142): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 1149:98](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L1149): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1150:19](https://github.com/spacetelescope/jwql/blob/2f89d287ae175305db267e3c33d86b2db3eae956/jwql/instrument_monitors/common_monitors/edb_telemetry_monitor.py#L1150): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent















##### Comment last updated at 2024-01-22 19:37:42 UTC

2024-01-17 17:06 UTC, BradleySappington requested changes
A few small changes.  Also please keep naming conventions common through all monitors (when appropriate).  It looks like `working_data_dir` and `output_data_dir` are the most used so would be easiest to stick with that.  I did not mark every instance where naming standard wasn't used.

2024-01-17 17:06 UTC, BradleySappington commented on jwql/instrument_monitors/common_monitors/readnoise_monitor.py
> +        output_filename = os.path.join(self.output_data_dir, '{}.png'.format(outname))
change docstring of "data_dir"

2024-01-17 17:06 UTC, BradleySappington commented on jwql/instrument_monitors/common_monitors/dark_monitor.py
> +    working_dir : str
this doesn't line up with other uses of working dir.  
outputs where outputs are placed (now on central store), working where data is kept and gathered to do calculations.  Is that understanding correct?

2024-01-17 17:06 UTC, BradleySappington commented on jwql/instrument_monitors/common_monitors/dark_monitor.py
>      data_dir : str
see above comment, but also, data_dir is renamed to `output_data_dir` in other modules. We should maintain naming conventions.

2024-01-17 17:06 UTC, BradleySappington commented on jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py
> +        self.working_dir = os.path.join(get_config()['working'], 'bad_pixel_monitor')
typo bug - should be `working_data_dir`

2024-01-18 19:12 UTC, york-stsci commented on jwql/instrument_monitors/common_monitors/readnoise_monitor.py
> +        output_filename = os.path.join(self.output_data_dir, '{}.png'.format(outname))
Change made.

2024-01-18 19:12 UTC, york-stsci commented on jwql/instrument_monitors/common_monitors/dark_monitor.py
> +    working_dir : str
That understanding is correct, with one nuance (on which more below).

2024-01-18 19:13 UTC, york-stsci commented on jwql/instrument_monitors/common_monitors/dark_monitor.py
>      data_dir : str
Change made.

2024-01-18 19:15 UTC, york-stsci commented on jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py
> +        self.working_dir = os.path.join(get_config()['working'], 'bad_pixel_monitor')
This is the nuance – some of the common monitors create a "data" directory underneath the working/output directory, usually to separate files by amplifier/detector/whatever, and it's *that* directory that's the working_data_dir. The directory specific to the monitor, by itself, is the working_dir. So essentially, working_data_dir is built from working_dir by appending on /data/ and potentially a further specifier.

2024-01-18 20:10 UTC, BradleySappington commented on jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py
> +        self.working_dir = os.path.join(get_config()['working'], 'bad_pixel_monitor')
My bad! I just opened up the whole file in a codespace, I see what you're doing now. Apologies for the false alarm!

2024-01-19 16:57 UTC, york-stsci commented
@BradleySappington I think I've made all the changes you requested, but I can't figure out how to tell the change request that.

2024-01-19 18:40 UTC, BradleySappington approved these changes

2024-01-19 18:41 UTC, BradleySappington commented
I approved, I think that should fix it aside from resolving conflicts and making sure the tests pass

2024-01-22 19:56 UTC, merged