WIP Update Bad Pixel Monitor to use Django DB Models
spacetelescope/jwql pull request #1497
Opened 2024-02-22 00:37 UTC by mfixstsci

2024-03-11 13:51 UTC, pep8speaks commented
Hello @mfixstsci, Thank you for updating !

* In the file [`jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py`](https://github.com/spacetelescope/jwql/blob/c1c855b7bbc2befda1b64429dd86c755b0840777/jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py):

> [Line 113:37](https://github.com/spacetelescope/jwql/blob/c1c855b7bbc2befda1b64429dd86c755b0840777/jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py#L113): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2024-03-11 14:40 UTC, bhilbert4 reviewed
These changes look good to me. What about in monitor_bad_pixel_bokeh.py? That should be querying the database in order to produce the plots, right?

2024-03-11 14:51 UTC, mfixstsci commented
> These changes look good to me. What about in monitor_bad_pixel_bokeh.py? That should be querying the database in order to produce the plots, right?

@bhilbert4 you are right, I just looked at the file. I will go ahead and update it.

2024-03-11 20:12 UTC, mfixstsci commented
@bhilbert4 okay, so the updates to `monitor_bad_pixel_bokeh.py` are in. I think should do it, let me know if I missed anything.

2024-11-06 20:49 UTC, mfixstsci commented
With @york-stsci 's updates are we prepared to merge? @bhilbert4 would you like to review the changes with Brian's changes in?

2024-11-07 20:32 UTC, bhilbert4 requested changes
This looks good to me. I hope you used a tool like Black rather than changing all those single quotes to double quotes manually. :) 

The only issue is that the migration file needs to be included.

2024-11-07 20:32 UTC, bhilbert4 commented on jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py
> +                self.new_bad_pix[bad_type] = (record.x_coord, record.y)
Should this be y_coord?

2024-11-08 17:08 UTC, york-stsci commented on jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py
> +                self.new_bad_pix[bad_type] = (record.x_coord, record.y)
Yes, it should be, based on the table definition.

2024-11-12 19:41 UTC, bhilbert4 approved these changes
LGTM. Thanks for clearing up the empty defaults!

2024-11-12 19:46 UTC, york-stsci commented
Looks good

2024-11-12 20:00 UTC, merged