WIP Update Dependencies and Requirements to use `pyproject.toml`
spacetelescope/jwql pull request #1528
Opened 2024-03-25 14:27 UTC by mfixstsci

Currently JWQL is using three different methods to track dependencies and build our python environment. It would be nice to shrink this down to one method and keep track of them in the `pyproject.toml`

2024-03-25 19:46 UTC, zacharyburnett commented
Looks good so far! You can likely remove `ruff` and `pytest`, and limit these dependencies only to those imported in the code. I'll draft up a release workflow too

2024-03-25 23:16 UTC, mfixstsci commented
@zacharyburnett Thanks for the PR, I went ahead and added the upper and lower bound pins. I also added the minimum python version. I guess the next steps would be to update the CI pipeline to get the tests passing. I am sure there is a nifty and much easier way to get the package installed with the pyproject.toml instead of executing a bunch of bash commands. Ideally the minimum version we would like to support at this point is 3.11 so the testing matrix will need to be updated to include python 3.11 and 3.12.

2024-03-26 19:37 UTC, mfixstsci commented
@zacharyburnett so close, looks like something with the mast portal is causing the test failure. I will investigate further tomorrow.

2024-05-13 15:36 UTC, zacharyburnett requested changes
@mfixstsci here's an `environment.yml` that includes `firefox`

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/ci.yml
```suggestion

defaults:
  run:
    shell: micromamba-shell {0}

```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/build.yml
> +
```suggestion

defaults:
  run:
    shell: micromamba-shell {0}

```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/ci.yml
> +      - uses: actions/setup-python@v5
```suggestion
      - uses: mamba-org/setup-micromamba@v1
```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/ci.yml
> +          cache-dependency-path: pyproject.toml
```suggestion
          environment-name: jwql-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yaml
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: none
          generate-run-shell: true
```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/build.yml
> +          python-version: ${{ matrix.python-version }}
```suggestion
      - uses: mamba-org/setup-micromamba@v1
         with:
          environment-name: jwql-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yaml
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: none
          generate-run-shell: true
```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/ci.yml
>          os: [ubuntu-latest, macos-latest]
```suggestion
        os: [ "ubuntu-latest", "macos-latest" ]
```

2024-05-13 15:36 UTC, zacharyburnett commented on .github/workflows/ci.yml
> +        python-version: ["3.11"]
```suggestion
        python-version: [ "3.11" ]
```

2024-05-14 18:08 UTC, zacharyburnett commented
superseded by #1568

2024-05-14 18:08 UTC, closed without merging