Adjust filters used in query
spacetelescope/jwql pull request #792
Opened 2021-09-10 16:20 UTC by tnking97

This PR includes the following updates:
-Add NIRSpec gratings as options in query form
-Use MIRI subarrays instead of apertures
-Adjust keywords used in query search
-A few adjustments for improved run time

2021-09-10 16:20 UTC, pep8speaks commented
Hello @tnking97, Thank you for submitting the Pull Request !



* In the file [`jwql/utils/constants.py`](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/constants.py):

> [Line 330:21](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/constants.py#L330): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent

* In the file [`jwql/utils/utils.py`](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/utils.py):

> [Line 192:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/utils.py#L192): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 553:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/utils.py#L553): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 560:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/utils/utils.py#L560): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`jwql/website/apps/jwql/data_containers.py`](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py):

> [Line 59:1](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py#L59): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 68:1](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py#L68): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 69:1](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py#L69): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 1181:9](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py#L1181): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 1272:21](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/data_containers.py#L1272): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent



* In the file [`jwql/website/apps/jwql/views.py`](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py):

> [Line 700:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L700): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 701:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L701): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 702:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L702): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 703:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L703): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 704:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L704): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 705:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L705): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 706:44](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L706): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 707:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L707): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 708:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L708): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 709:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L709): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 710:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L710): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 711:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L711): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 712:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L712): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 713:13](https://github.com/spacetelescope/jwql/blob/037d170d00e5d86acb5b42c3a0dadb891aaeae09/jwql/website/apps/jwql/views.py#L713): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

If you have not done so, please consult the [`jwql` Style Guide](https://github.com/spacetelescope/jwql/blob/main/style_guide/README.md)

2021-09-10 16:42 UTC, tnking97 commented
I think it would be best to keep the updated change (where FGS has multiple options for `READPATT_PER_INST` in the `constants.py` file).

On another note, I am having ongoing discussions with the MAST team regarding run time of queries and effects of wildcard parameters; hopefully some of these changes can be implemented shortly.

2021-09-27 20:44 UTC, bourque requested changes
Thank you for all of these changes @tnking97!  They all look really good to me!

I just had some (hopefully very minor) comments/questions, otherwise I think the code changes are good to go.

I still need to test this branch out on the dev server to make sure it works there, but things seem to be working when I test this locally.

2021-09-27 20:44 UTC, bourque commented on jwql/website/apps/jwql/data_containers.py
> +                      "filters": query_filters}
Nice investigative work here to figure out how to get around the wildcard parameter!

2021-09-28 15:13 UTC, tnking97 commented on jwql/utils/utils.py
> +def get_instrument_from_filename(filename):
Thank you for this idea!

2021-09-28 17:29 UTC, tnking97 commented
Thank you for your review, @bourque ! I've made updates to address all of the suggestions.

2021-09-29 14:45 UTC, bourque approved these changes
Thanks again @tnking97 for all of these changes!

Upon testing, it looks like this is all working! (albeit slowly; perhaps we can iterate on it in the future to try to improve the speeds further).

2021-09-29 14:45 UTC, merged