WIP Plot non-numerical mnemonic dataset
spacetelescope/jwql pull request #868
Opened 2022-02-04 21:55 UTC by mfixstsci

Many of the mnemonic datasets used by the EDB contain `date` and non-numerical `euvalues`.

Current approach:
* If unique possible values of `euvalues` is `> 1 & <=4` then we will plot the data.
* If unique possible values of `euvalues` is `> 4` then we will display a table
* If values are numeric, just generate the expected figure.

2022-02-08 15:23 UTC, pep8speaks commented
Hello @mfixstsci, Thank you for updating !

* In the file [`jwql/edb/engineering_database.py`](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/edb/engineering_database.py):

> [Line 162:64](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/edb/engineering_database.py#L162): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 207:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/edb/engineering_database.py#L207): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 316:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/edb/engineering_database.py#L316): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`jwql/website/apps/jwql/data_containers.py`](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py):

> [Line 59:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L59): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 68:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L68): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 69:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L69): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 375:41](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L375): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 607:5](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L607): [E115](https://duckduckgo.com/?q=pep8%20E115) expected an indented block (comment)
> [Line 607:5](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L607): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 935:13](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L935): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 936:17](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L936): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 974:1](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L974): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1103:31](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L1103): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 1191:9](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L1191): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 1279:21](https://github.com/spacetelescope/jwql/blob/d0573ab92b5aa7e159687e67a3abd0b7a4931686/jwql/website/apps/jwql/data_containers.py#L1279): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2022-02-08 15:31 UTC, mfixstsci commented
Ready for review, I copied the code that "Explore the EDB mnemonic inventory" uses to generate the table. I am sure there is a way to synergize the code there and in the method I wrote to generate a table for mnemonic data with too many unique text values.

Examples to Test:
------------------
* Defaults will return expected plot
* Test parameters that only has 3 or 4 unique values (`SA_ZSLEWST`, `2021-09-01 00:00:00.000`, `2021-09-03 00:01:00.000`)
* Test parameters for text that has too many unique strings to plot (`ICTM_EVENT_MSG`, `2021-09-01 00:00:00.000`, `2021-10-01 00:01:00.000`)

Try it out locally and tell me what you think!

2022-02-15 16:27 UTC, bourque requested changes
@mfixstsci Thanks for these changes, they look and work great when I test them out!  I just have a few questions in the review.

2022-02-15 16:27 UTC, bourque commented on jwql/edb/engineering_database.py
> +        import copy
Could these be moved up to the top of the module with the other imports?

2022-02-15 16:27 UTC, bourque commented on jwql/edb/engineering_database.py
> +from tokenize import PlainToken
Could these be removed?  I don't see them being used in the code.

2022-02-15 16:27 UTC, bourque commented on jwql/edb/engineering_database.py
> +from enum import unique
I see `numpy.unique` being used in the code, but I don't see `enum.unique` being used.  Could this be removed?

2022-02-18 13:57 UTC, bourque approved these changes
Thanks for the updates @mfixstsci, this looks great!

2022-02-18 14:10 UTC, merged